server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://hvnkljupeanlmf:4ab4edf44170e00dd7f1651fef1c8d32a7e94344b93720181bfff63b3473a6c7@ec2-3-217-219-146.compute-1.amazonaws.com:5432/d259vdn0tjmoae
    username: hvnkljupeanlmf
    password: 4ab4edf44170e00dd7f1651fef1c8d32a7e94344b93720181bfff63b3473a6c7
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    gerate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
